MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        MvcDbStokEntities1 db = new MvcDbStokEntities1();
        public ActionResult Index()  
        {
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }
        [HttpGet]

        public ActionResult UrunEkle() //Kategorileri listeleme işlemi
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value=i.KATEGORIID.ToString()
                                             }).ToList();   
            ViewBag.dgr = degerler;
            return View();
        }

        [HttpPost]

        public ActionResult UrunEkle(TBLURUNLER p1) //Ürün ekleme işlemi
        {
            var ktgr = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktgr;
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult SIL(int id) //Ürün silme işlemi
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult UrunGetir(int id) //Ürün getirme işlemi
        {
            var urun = db.TBLURUNLER.Find(id);

            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;

            return View("UrunGetir", urun); 
        }

        public ActionResult Guncelle(TBLURUNLER p) //Ürün güncelleme işlemi
        {
            var urun = db.TBLURUNLER.Find(p.URUNID);    
            urun.URUNAD = p.URUNAD;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.FIYAT = p.FIYAT;
            //urun.URUNKATEGORI = p.URUNKATEGORI;
            var ktgr = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktgr.KATEGORIID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.Entity;
@model  List<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>Ürün ID</th>
            <th>Ürün Adı</th>
            <th>Marka</th>
            <th>Kategori</th>
            <th>Fiyat</th>
            <th>Stok</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>
                <th>@urn.URUNID</th>
                <td>@urn.URUNAD</td>
                <td>@urn.MARKA</td>
                <td>@urn.TBLKATEGORILER.KATEGORIAD</td>
                <td>@urn.FIYAT</td>
                <td>@urn.STOK</td>
                <td><a href="/URUN/SIL/@urn.URUNID" class="btn btn-danger">SİL</a></td>
                <td><a href="/URUN/UrunGetir/@urn.URUNID" class="btn btn-success">GÜNCELLE</a></td>
            </tr>
        }
</table>
<a href="/URUN/UrunEkle/" class="btn btn-primary">YENİ ÜRÜN EKLE</a>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>


<link href="~/Content/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
<script>
    $('#tbl1').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Turkish.json"
        }
    });
</script>

MvcStok/Views/Urun/UrunEkle.cshtml
@model MvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">

    <div>
        <label>Ürün Adı</label>
        <input type="text" name="URUNAD" class="form-control" required="" maxlength="50"/>
    </div>
    <div style="margin-top:10px">
        <label>Markası</label>
        <input type="text" name="MARKA" class="form-control" required="" placeholder="Marka ismi"/>
    </div>
    <div style="margin-top:10px">
        <label>Kategori Seçiniz</label>
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new {@class = "form-control"} )
    </div>
    <div style="margin-top:10px">
        <label>Fiyatı</label>
        <input type="text" name="FIYAT" class="form-control" />
    </div>
    <div style="margin-top:10px">
        <label>Stok Adet</label>
        <input type="text" name="STOK" class="form-control" />
    </div>

    <div style="margin-top:10px">
        <button class="btn btn-info">Ürün Ekle</button>
    </div>
</form>

MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.URUNID)
        @Html.TextBoxFor(x => x.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.URUNAD)
        @Html.TextBoxFor(x => x.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.MARKA)
        @Html.TextBoxFor(x => x.MARKA, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.URUNKATEGORI)
        @*@Html.TextBoxFor(x => x.URUNKATEGORI, new { @class = "form-control" })*@
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID,(List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.FIYAT)
        @Html.TextBoxFor(x => x.FIYAT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.STOK)
        @Html.TextBoxFor(x => x.STOK, new { @class = "form-control" })
        <br />
    </div>
    <input type="submit" value="Ürün Güncelle" class="btn btn-primary" />
}