MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        MvcDbStokEntities1 db = new MvcDbStokEntities1();
        public ActionResult Index(string p) //Müşterileri listeleme işlemi
        {
            var degerler = from d in db.TBLMUSTERILER select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());
            //var degerler = db.TBLMUSTERILER.ToList();
            //return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1) //Müşteri ekleme işlemi
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }

            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();
        }

        public ActionResult SIL(int id) //Müşteri silme işlemi
        {
            var musterı = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musterı);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir", mus);
        }

        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var mus = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            mus.MUSTERIAD = p1.MUSTERIAD;
            mus.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity;
@model  List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Musteri", FormMethod.Get))
{
    <p>
        <b>Aranacak Müşteri Adı:</b>  @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>

}

<table class="table table-bordered">
    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri Adı</th>
        <th>Müşteri Soyadı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Alet</th>
    </tr>
    <tbody>
        @foreach (var mus in Model)
        {
            <tr>
                <td>@mus.MUSTERIID</td>
                <td>@mus.MUSTERIAD</td>
                <td>@mus.MUSTERISOYAD</td>
                <td><a href="/MUSTERI/SIL/@mus.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/MUSTERI/MusteriGetir/@mus.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
                <td>@Html.ActionLink("SİL BUTONU", "SIL", new { id = mus.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten silmek istiyor musunuz?')" })</td>
            </tr>
        }
</table>
<a href="/MUSTERI/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Musteri/MusteriGetir.cshtml
@model  MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MUSTERIID)
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })

        <br/>
        @Html.LabelFor(m => m.MUSTERIAD)
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })

        <br/>
        @Html.LabelFor(m => m.MUSTERISOYAD)
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Müşteri Güncelle</button>
    </div>
}

MvcStok/Views/Musteri/YeniMusteri.cshtml
@model   MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">

    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(x => x.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.MUSTERIAD, "", new { @class = "text-danger" })
    </div>
    <div style="margin-top:10px">
        <label>Müşteri Soyadı</label>
        <input type="text" name="MUSTERISOYAD" class="form-control" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-info" id="btn1">Müşteri Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Müşteri Eklendi');
        });
    </script>
</form>